module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,html,mdx}"],
  darkMode: "class",
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        /* Primary Colors */
        primary: {
          DEFAULT: "var(--primary-bg)",
          dark: "var(--primary-bg-dark)",
          light: "var(--primary-bg-light)",
        },
        /* Secondary Colors */
        secondary: {
          DEFAULT: "var(--secondary-bg)",
          light: "var(--secondary-bg-light)",
          transparent: "var(--secondary-bg-transparent)",
        },
        /* Neutral Colors */
        neutral: {
          white: "var(--neutral-bg-white)",
          light: "var(--neutral-bg-light)",
          gray: "var(--neutral-bg-gray)",
          blue: "var(--neutral-bg-blue)",
          cyan: "var(--neutral-bg-cyan)",
          purple: "var(--neutral-bg-purple)",
          silver: "var(--neutral-bg-silver)",
        },
        /* Text Colors */
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          dark: "var(--text-dark)",
          white: "var(--text-white)",
          "accent-teal": "var(--text-accent-teal)",
          "accent-blue": "var(--text-accent-blue)",
        },
        /* Border Colors */
        border: {
          primary: "var(--border-primary)",
          secondary: "var(--border-secondary)",
          accent: "var(--border-accent)",
          light: "var(--border-light)",
        },
        /* Component Colors */
        header: {
          background: "var(--header-bg)",
          text: "var(--header-text)",
        },
        button: {
          "primary-bg": "var(--button-primary-bg)",
          "primary-text": "var(--button-primary-text)",
          "secondary-bg": "var(--button-secondary-bg)",
          "secondary-text": "var(--button-secondary-text)",
          "outline-border": "var(--button-outline-border)",
          "outline-text": "var(--button-outline-text)",
        },
        link: {
          text: "var(--link-text)",
          hover: "var(--link-hover)",
        },
        card: {
          background: "var(--card-bg)",
          border: "var(--card-border)",
        },
        input: {
          border: "var(--input-border)",
          text: "var(--input-text)",
          placeholder: "var(--input-placeholder)",
        },
        footer: {
          background: "var(--footer-bg)",
          text: "var(--footer-text)",
        },
      },
      /* Font Sizes */
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        md: "var(--font-size-md)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",
        "5xl": "var(--font-size-5xl)",
        "6xl": "var(--font-size-6xl)",
        "7xl": "var(--font-size-7xl)",
      },
      /* Font Weights */
      fontWeight: {
        normal: "var(--font-weight-normal)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
      },
      /* Line Heights */
      lineHeight: {
        xs: "var(--line-height-xs)",
        sm: "var(--line-height-sm)",
        base: "var(--line-height-base)",
        md: "var(--line-height-md)",
        lg: "var(--line-height-lg)",
        xl: "var(--line-height-xl)",
        "2xl": "var(--line-height-2xl)",
        "3xl": "var(--line-height-3xl)",
        "4xl": "var(--line-height-4xl)",
        "5xl": "var(--line-height-5xl)",
        "6xl": "var(--line-height-6xl)",
        "7xl": "var(--line-height-7xl)",
        "8xl": "var(--line-height-8xl)",
        "9xl": "var(--line-height-9xl)",
      },
      /* Spacing - Margin */
      margin: {
        xs: "var(--margin-xs)",
        sm: "var(--margin-sm)",
        md: "var(--margin-md)",
        lg: "var(--margin-lg)",
        xl: "var(--margin-xl)",
        "2xl": "var(--margin-2xl)",
        "3xl": "var(--margin-3xl)",
        "4xl": "var(--margin-4xl)",
        "5xl": "var(--margin-5xl)",
        "6xl": "var(--margin-6xl)",
        "7xl": "var(--margin-7xl)",
        "8xl": "var(--margin-8xl)",
        "9xl": "var(--margin-9xl)",
        "10xl": "var(--margin-10xl)",
        "11xl": "var(--margin-11xl)",
        "12xl": "var(--margin-12xl)",
        "13xl": "var(--margin-13xl)",
        "14xl": "var(--margin-14xl)",
        "15xl": "var(--margin-15xl)",
        "16xl": "var(--margin-16xl)",
        "17xl": "var(--margin-17xl)",
        "18xl": "var(--margin-18xl)",
        "19xl": "var(--margin-19xl)",
        "20xl": "var(--margin-20xl)",
        "21xl": "var(--margin-21xl)",
        "22xl": "var(--margin-22xl)",
        "23xl": "var(--margin-23xl)",
        "24xl": "var(--margin-24xl)",
        "25xl": "var(--margin-25xl)",
        "26xl": "var(--margin-26xl)",
      },
      /* Spacing - Padding */
      padding: {
        xs: "var(--padding-xs)",
        sm: "var(--padding-sm)",
        md: "var(--padding-md)",
        lg: "var(--padding-lg)",
        xl: "var(--padding-xl)",
        "2xl": "var(--padding-2xl)",
        "3xl": "var(--padding-3xl)",
        "4xl": "var(--padding-4xl)",
        "5xl": "var(--padding-5xl)",
        "6xl": "var(--padding-6xl)",
        "7xl": "var(--padding-7xl)",
        "8xl": "var(--padding-8xl)",
        "9xl": "var(--padding-9xl)",
        "10xl": "var(--padding-10xl)",
        "11xl": "var(--padding-11xl)",
        "12xl": "var(--padding-12xl)",
        "13xl": "var(--padding-13xl)",
        "14xl": "var(--padding-14xl)",
        "15xl": "var(--padding-15xl)",
        "16xl": "var(--padding-16xl)",
        "17xl": "var(--padding-17xl)",
        "18xl": "var(--padding-18xl)",
        "19xl": "var(--padding-19xl)",
        "20xl": "var(--padding-20xl)",
        "21xl": "var(--padding-21xl)",
        "22xl": "var(--padding-22xl)",
        "23xl": "var(--padding-23xl)",
        "24xl": "var(--padding-24xl)",
        "25xl": "var(--padding-25xl)",
        "26xl": "var(--padding-26xl)",
      },
      /* Spacing - Gap */
      gap: {
        xs: "var(--gap-xs)",
        sm: "var(--gap-sm)",
        md: "var(--gap-md)",
        lg: "var(--gap-lg)",
        xl: "var(--gap-xl)",
        "2xl": "var(--gap-2xl)",
        "3xl": "var(--gap-3xl)",
        "4xl": "var(--gap-4xl)",
        "5xl": "var(--gap-5xl)",
        "6xl": "var(--gap-6xl)",
        "7xl": "var(--gap-7xl)",
        "8xl": "var(--gap-8xl)",
        "9xl": "var(--gap-9xl)",
        "10xl": "var(--gap-10xl)",
        "11xl": "var(--gap-11xl)",
        "12xl": "var(--gap-12xl)",
        "13xl": "var(--gap-13xl)",
        "14xl": "var(--gap-14xl)",
        "15xl": "var(--gap-15xl)",
        "16xl": "var(--gap-16xl)",
        "17xl": "var(--gap-17xl)",
        "18xl": "var(--gap-18xl)",
        "19xl": "var(--gap-19xl)",
        "20xl": "var(--gap-20xl)",
      },
      /* Border Radius */
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        "4xl": "var(--radius-4xl)",
        "5xl": "var(--radius-5xl)",
        "6xl": "var(--radius-6xl)",
        "7xl": "var(--radius-7xl)",
        "8xl": "var(--radius-8xl)",
        "9xl": "var(--radius-9xl)",
        "10xl": "var(--radius-10xl)",
        "11xl": "var(--radius-11xl)",
        "12xl": "var(--radius-12xl)",
        "13xl": "var(--radius-13xl)",
        "14xl": "var(--radius-14xl)",
        "15xl": "var(--radius-15xl)",
      },
      /* Border Width */
      borderWidth: {
        thin: "var(--border-width-thin)",
        medium: "var(--border-width-medium)",
      },
      /* Box Shadow */
      boxShadow: {
        card: "var(--card-shadow)",
      },
    },
  },
  plugins: [],
};
